---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
First, we are going to unzip the dataset and load it from the csv file:

```{R}
unzip("activity.zip")
data <- read.csv("activity.csv")
data$date <- as.Date(data$date, format = "%Y-%m-%d")
```

Note that we convert the "date" column values to the `Date` class.

## What is mean total number of steps taken per day?

Next, we calculate the total number of steps per day using the `aggregate` function. We plot a histogram of the total number of steps per day and take the mean and the median of this value

```{R}
stepsPerDay <- aggregate(list(totalSteps = data$steps), by = list(date = data$date), FUN = sum)
hist(stepsPerDay$totalSteps, main = "Histogram of total number of steps per day", xlab = "Steps per day")
mean(stepsPerDay$totalSteps, na.rm = TRUE)
median(stepsPerDay$totalSteps, na.rm = TRUE)
```


## What is the average daily activity pattern?

We also aggregate the data by the 5 minute interval, so that we can take the average number of steps taken across all days, showing this result in a time series plot.

```{R}
averageStepsPerInterval <- aggregate(steps ~ interval, data, mean)
plot(averageStepsPerInterval$interval, averageStepsPerInterval$steps, type = "l", main = "Average number of steps per 5-minute interval", xlab = "Interval identifier", ylab = "Average number of steps")
```

Using the data, we find out the interval which has, in average, the maximum number of steps taken.

```{R}
intervalWithMaximumNumberOfStepsInAverage <- averageStepsPerInterval[averageStepsPerInterval$steps == max(averageStepsPerInterval$steps), "interval"]
```

We conclude that the `r intervalWithMaximumNumberOfStepsInAverage`th interval is the interval with the maximum number of steps in average. 

## Imputing missing values

To calculate the number of missing values in the dataset, we use the complete.cases function

```{R}
nrow(data[!complete.cases(data), ])
```

All the `NA` values come from the `steps` column

```{R}
nrow(data[is.na(data$steps), ])
```

We choose to fill the `NA` values in the `steps` column with the average number of steps in that particular 5-minute interval of the day.

```{R}
newData <- merge(data[is.na(data$steps), c("date", "interval")], averageStepsPerInterval, by = "interval")
```

Then, we recreate our original data by combining the rows that do not have `NA` with the data that has the average steps by interval instead of `NA` values:

```{R}
newData <- rbind(data[!is.na(data$steps), ], newData)
newData <- newData[order(newData$date), ]
```
Inspecting the `head` of the new data shows that the `NA` values have been replaced

```{R, echo = FALSE}
head(newData)
```
To verify the impact of replacing the `NA`values, we plot a histogram of the total number of steps each day and take the mean and median

```{R}
stepsPerDay <- aggregate(list(totalSteps = newData$steps), by = list(date = newData$date), FUN = sum)
hist(stepsPerDay$totalSteps, main = "Histogram of total number of steps per day", xlab = "Steps per day")
mean(stepsPerDay$totalSteps)
median(stepsPerDay$totalSteps)
```
Compared with the results generated with the original data, we can see there is a small variation in the histogram shape and the median value.

## Are there differences in activity patterns between weekdays and weekends?

To find out the differences in activity patterns between weekdays and weekends we first subset our data using the weekday of the dates. 

```{R}
weekendData <- newData[as.POSIXlt(newData$date)$wday %in% c(0, 6), ]
weekdayData <- newData[!(as.POSIXlt(newData$date)$wday %in% c(0, 6)), ]
```
Next, we recombine the data adding a factor column that tells us if the date is a weekend or a weekday

```{R}
dayType <- factor(c("weekday", "weekend"))
newDataWithDayType <- rbind(cbind(weekendData, list(dayType = dayType[2])), cbind(weekdayData, list(dayType = dayType[1])))
```

Finally, we calculate the average number of steps per 5-minute interval during weekends and weekdays and plot these values in a two graph panel, using the `lattice` library

```{R}
library(lattice)
averageStepsPerIntervalAndDayType <- aggregate(steps ~ interval + dayType, newDataWithDayType, mean)
xyplot(steps ~ interval | dayType, averageStepsPerIntervalAndDayType, type = "l", layout = c(1, 2), xlab = "Interval identifier", ylab = "Average number of steps")
```
